services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - bsn-network
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - bsn-network

  # --- PGADMIN (Visualisation DB) ---
  pgadmin:
    container_name: pgadmin-bsn
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - bsn-network
    restart: unless-stopped

  # --- SONARQUBE INFRA ---
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube-bsn
    depends_on:
      - sonar-db
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - bsn-network
    restart: unless-stopped

  sonar-db:
    image: postgres:15
    container_name: postgres-sonar-bsn
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonar-db-data:/var/lib/postgresql/data
    networks:
      - bsn-network
    restart: unless-stopped

networks:
  bsn-network:
    driver: bridge

volumes:
  postgres-data:
  sonar-db-data:
  sonarqube_data:
  sonarqube_extensions: