name: Backend Check Unblocker

on:
  pull_request:
    paths-ignore:
      - 'book-network/**'
      - 'docker/backend/**'
      - '.github/workflows/pipeline-backend.yml'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Skip Backend Tests
        run: echo "No backend changes detected. Skipping required checks."