name: Check Unblocker

on:
  pull_request:
    paths-ignore:
      - 'book-network/**'
      - 'book-network-ui/**'
      - 'docker/backend/**'
      - 'docker/frontend/**'
      - 'docker-compose.yml'
      - '.github/workflows/pipeline-backend.yml'
      - '.github/workflows/pipeline-frontend.yml'


jobs:
  unblock-backend:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - name: Skip Backend Tests
        run: echo "No backend changes detected. Skipping required checks."
  
  unblock-frontend:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - name: Skip Frontend Tests
        run: echo "No frontend changes detected. Skipping required checks."